"""empty message

Revision ID: aa675715e812
Revises: 
Create Date: 2022-07-30 09:41:19.442144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa675715e812'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('session_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('era', sa.String(), nullable=True),
    sa.Column('runtime', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('user_data',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('seen_it', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_data')
    op.drop_table('session')
    # ### end Alembic commands ###
