"""empty message

Revision ID: dddc3db51f0d
Revises: 31bf761b9f0c
Create Date: 2022-07-29 14:16:52.614597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dddc3db51f0d'
down_revision = '31bf761b9f0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_data',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('seen_it', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_table('user_account')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('seen_it', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='user_account_pkey')
    )
    op.drop_table('user_data')
    # ### end Alembic commands ###
